Added method for show ads
optimist-dev/vk_bridge pull request #32
Opened 2021-02-27 05:16 UTC by syfulin

Demo:
https://user-images.githubusercontent.com/20333151/109376177-6a429080-78f5-11eb-9571-84277f7a7b37.MP4

2021-03-01 09:58 UTC, otopba commented
@syfulin Hi! CI failed. Please check your dependencies

2021-03-01 11:03 UTC, sanekyy requested changes

2021-03-01 11:03 UTC, sanekyy commented on CHANGELOG.md
> +## 1.2.7
Нужно поставить версию `1.3.0`, т.к. это добавление нового функционала, а не фикс бага

2021-03-01 11:03 UTC, sanekyy commented on CHANGELOG.md
> +- Added method for dshow ads
`dshow` -> `show`

2021-03-01 11:03 UTC, sanekyy commented on lib/src/bridge/vk_bridge.dart
> +  /// Possible options: ​preloader, reward, interstitial.
Если есть возможность/желание, сделай формат рекламы не строчкой, а enum

или же добавь TODO

2021-03-03 09:33 UTC, sanekyy approved these changes

2021-03-03 10:09 UTC, otopba commented
@syfulin We have problems with libs. We will fix it today

2021-03-03 10:11 UTC, syfulin commented
> @syfulin We have problems with libs. We will fix it today

2021-03-03 10:13 UTC, syfulin commented
Случайно закрыл Pull request

2021-03-03 10:39 UTC, sanekyy commented
@syfulin 
можешь пока не тратить время на фикс CI и зависимостей, мы пофиксим это сегодня, зальём в мастер, ты подтянешь в свою ветку и мы смёржим этот PR

2021-03-03 10:46 UTC, otopba commented
Сдался, тоже напишу на русском )))
Кажется не получится просто так поправить без оверайдов. Давайте дождемся вот этого решения:
https://github.com/google/built_value.dart/issues/987

2021-03-09 12:43 UTC, otopba commented
@syfulin Подмержи пожалуйста master в эту ветку

2021-03-12 15:57 UTC, syfulin commented
> @syfulin Подмержи пожалуйста master в эту ветку

Примите Pull Request c Null Safety? И потом я на эту версию добавлю новые методы для VK Bridge?

2021-03-14 07:01 UTC, closed without merging