Null Safety
optimist-dev/vk_bridge pull request #34
Opened 2021-03-06 23:20 UTC by festelo

`launchParams` и `launchHash` немного проблемные.
Я их сделал nullable. 

Можно вынести их в конструктор и объявить как final, а метод `init()` заменить на `static Future<VKBridge> load()`, тогда nullable не нужен, но это ломает `static final VKBridge instance`.

Можно пометить их keyword'ом late, но в F.A.Q. [написано](https://dart.dev/null-safety/faq) "Only mark a field late if you are sure it is always initialized before it is used.". Мы не можем быть уверены, т.к. метод `init()` вызывается пользователями либы.

-------

* Поменял @required на required, остальные поля сделал nullable. 
* Для built поменял @nullable на T? 
* Обновил зависимости до поддерживающих null-safety
* Тайпкасты кое-где добавил (dynamic может быть nullable, built в некоторых методах поменял параметры с dynamic на Object, который не может быть nullable)

2021-03-07 01:34 UTC, festelo commented on lib/src/bridge/vk_bridge_web.dart
data может быть null

2021-03-07 16:54 UTC, sanekyy commented
Отличная работа. На днях посмотрим.

2021-03-09 12:44 UTC, otopba commented
@festelo Подмержи пожалуйста master в эту ветку

2021-03-09 12:59 UTC, festelo commented
Готово

2021-03-09 13:32 UTC, festelo commented on lib/src/bridge/vk_bridge_web.dart
> +      if (error == null) {
Вообще, throw null же не компилируется. Получается error никогда не может быть null, т.к. decodedJson не null?

2021-03-09 13:36 UTC, festelo commented on lib/src/bridge/vk_bridge_web.dart
>        final Object decodedJson = jsonDecode(jsonError) as Object;
а зачем сериализовать, а потом десериализовать?

2021-04-06 09:30 UTC, sanekyy commented on lib/src/bridge/vk_bridge_web.dart
>        final Object decodedJson = jsonDecode(jsonError) as Object;
Ответ на этот вопрос есть в нашем докладе про этот пакет:)

Если в кратце: мы не можем десериализовать json объект пришедший из JS мира, поэтому перегоняем его в строчку, а потом в дартовый JSON

2021-04-06 09:33 UTC, sanekyy commented
> Мы не можем быть уверены, т.к. метод init() вызывается пользователями либы и может быть не вызван.

Давай сделаем late, т.к. обращение к другим методам до вызова `init()` не подразумевается, т.е. это будет заведомо неверное использование пакета.

2021-04-06 09:52 UTC, sanekyy commented on lib/src/bridge/vk_bridge_web.dart
> +      if (error == null) {
Получается так

2021-04-06 09:55 UTC, sanekyy requested changes

2021-04-06 09:55 UTC, sanekyy commented on pubspec.yaml
>  version: 1.2.6+1
версию нужно поднять до 2.0.0 и CHANGELOG оформить

2021-08-17 19:22 UTC, w3ggy commented on lib/src/bridge/vk_bridge_web.dart
>      final decodedJsonEvent = jsonDecode(jsonEvent) as Map<String, Object>;
`final decodedJsonEvent = jsonDecode(jsonEvent) as Map<String, dynamic>;`

тут должно быть так, сейчас падает просто на парсинге )

2021-08-17 19:50 UTC, sanekyy commented
@festelo 
Привет
Можем добить PR?

2021-08-17 21:24 UTC, festelo commented
привет. Да, на днях посмотрю

2021-08-20 21:55 UTC, festelo commented on lib/src/bridge/vk_bridge_web.dart
>      final decodedJsonEvent = jsonDecode(jsonEvent) as Map<String, Object>;
Я 5 месяцев назад сделал коммит, изменив эту строчку на  `final decodedJsonEvent = Map<String, Object>.from(jsonDecode(jsonEvent) as Map);`, потому что у меня тоже не работало. Но запушить не запушил.

Наверное, правильно было бы все-таки <String, dynamic> использовать, мало ли что от API может прийти, поменял на твой вариант.

2021-08-20 22:02 UTC, festelo commented
Должно быть все ок

2021-08-21 10:32 UTC, sanekyy commented
> > Мы не можем быть уверены, т.к. метод init() вызывается пользователями либы и может быть не вызван.
> 
> Давай сделаем late, т.к. обращение к другим методам до вызова `init()` не подразумевается, т.е. это будет заведомо неверное использование пакета.

@festelo Давай сделаем late всё таки? Можем в доке к этим двум полям добавить что они  инициализируются при вызове init()

2021-08-23 12:04 UTC, sanekyy requested changes

2021-08-23 12:04 UTC, sanekyy commented on lib/src/bridge/vk_bridge_web.dart
> +  late final String launchHash;
Давай оставим публичный геттер и приватное поле, чтобы не было возможности присвоить в launchHash что-то другое снаружи и упасть

@otopba что скажешь?

2021-08-23 12:14 UTC, festelo commented on lib/src/bridge/vk_bridge_web.dart
> +  late final String launchHash;
Оно за абстракцией скрыто, так что не это не особо страшно. Но и не хорошо, поменял.

2021-08-23 12:16 UTC, sanekyy commented on lib/src/bridge/vk_bridge_web.dart
> +  late final String launchHash;
Спасибо!

2021-08-23 12:16 UTC, sanekyy approved these changes

2021-08-23 12:18 UTC, merged