Fix map cast
optimist-dev/vk_bridge pull request #35
Opened 2021-03-07 01:24 UTC by festelo

Получал вот такую ошибку - Uncaught TypeError: Instance of '_JsonMap': type '_JsonMap' is not a subtype of type 'Map<String, Object>'.
Т.е. нельзя закастовать `dynamic (_JsonMap)` к `Map<String, Object>`, потому что _JsonMap не наследуется от Map<String, Object>. Если в сурцы заглянуть, они вот здесь - https://github.com/dart-lang/sdk/blob/master/sdk/lib/_internal/js_runtime/lib/convert_patch.dart, то можно увидеть, что наследуется оно от Map<String, dynamic>. dynamic != Object.

2021-03-09 12:45 UTC, otopba approved these changes

2021-03-09 12:45 UTC, otopba requested changes
LGTM, только нужно повысить версию и написать сhangelog

2021-03-09 13:23 UTC, festelo commented
Пойдет?

2021-03-09 13:26 UTC, otopba commented
> Пойдет?

Да, супер

2021-03-09 13:27 UTC, otopba approved these changes

2021-04-06 09:24 UTC, sanekyy approved these changes

2021-04-06 09:25 UTC, merged

2021-04-06 09:25 UTC, otopba commented
Сори за долгий ответ. Вмержено!