VK Bridge Game Events
optimist-dev/vk_bridge pull request #50
Opened 2023-02-02 23:19 UTC by Evgenii-Zinner

Two functions from VK Bridge for games was added, 
VKWebAppShowInviteBox Send an Invitation;
VKWebAppShowLeaderBoardBox Open the Leaderboard.

2023-02-03 07:45 UTC, sanekyy requested changes

2023-02-03 07:45 UTC, sanekyy commented on lib/src/bridge/vk_bridge.dart
> +  /// Platforms: iOS, Android, Web, Mobile Web
There is no Web support or there is an error in official documentation.

https://dev.vk.com/bridge/VKWebAppShowLeaderBoardBox

2023-02-03 07:45 UTC, sanekyy commented on lib/src/bridge/vk_bridge.dart
> +  Future<VKWebAppBoolResult> showLeaderBoardBox();
As I see there is a optional parameter `user_result`

https://dev.vk.com/bridge/VKWebAppShowLeaderBoardBox

2023-02-03 07:45 UTC, sanekyy commented on lib/src/bridge/vk_bridge.dart
> +  Future<VKWebAppBoolResult> showInviteBox();
Result contains `notSentIds`

https://dev.vk.com/bridge/VKWebAppShowInviteBox

2023-02-03 07:45 UTC, sanekyy commented on lib/src/bridge/vk_bridge.dart
> +  Future<VKWebAppBoolResult> showInviteBox();
As I see there is a optional parameter `requestKey`

2024-01-24 13:37 UTC, otopba commented
@Evgenii-Zinner Hello! Is this PR still relevant?

2024-01-26 13:01 UTC, closed without merging